const MaterialRequestMockData = [
    {
      id: 1,
      sno: 1,
      reqId: "REQ-1001",
      materialsCount: 10,
      description: "Request for electrical components",
      dateOfReq: "2025-02-28",
      status: "Pending",
      nestedData: [
        {
          materialName: "Copper Wire",
          quantityRequested: 50,
          requestedTo: "Electrical Dept",
          dateOfRequirement: "2025-03-05",
          materialPurpose: "Wiring for new building",
          priority: "High",
          status: "Approved",
          action: "View",
        },
        {
          materialName: "LED Bulbs",
          quantityRequested: 20,
          requestedTo: "Procurement",
          dateOfRequirement: "2025-03-07",
          materialPurpose: "Lighting upgrade",
          priority: "Medium",
          status: "Pending",
          action: "Approve",
        },
        {
          materialName: "Circuit Breakers",
          quantityRequested: 10,
          requestedTo: "Engineering",
          dateOfRequirement: "2025-03-10",
          materialPurpose: "Power distribution",
          priority: "Critical",
          status: "Rejected",
          action: "Reapply",
        },
        {
          materialName: "Switchboards",
          quantityRequested: 5,
          requestedTo: "Engineering",
          dateOfRequirement: "2025-03-08",
          materialPurpose: "Panel installation",
          priority: "High",
          status: "Approved",
          action: "View",
        },
        {
          materialName: "Insulation Tape",
          quantityRequested: 30,
          requestedTo: "Maintenance",
          dateOfRequirement: "2025-03-06",
          materialPurpose: "Wire safety",
          priority: "Low",
          status: "Pending",
          action: "Approve",
        },
        {
          materialName: "Voltage Stabilizer",
          quantityRequested: 3,
          requestedTo: "Electrical Dept",
          dateOfRequirement: "2025-03-09",
          materialPurpose: "Voltage regulation",
          priority: "Critical",
          status: "Approved",
          action: "View",
        },
        {
          materialName: "Power Strips",
          quantityRequested: 15,
          requestedTo: "Procurement",
          dateOfRequirement: "2025-03-11",
          materialPurpose: "Workstation power management",
          priority: "Medium",
          status: "Pending",
          action: "Approve",
        },
        {
          materialName: "Extension Cords",
          quantityRequested: 25,
          requestedTo: "Procurement",
          dateOfRequirement: "2025-03-12",
          materialPurpose: "Temporary wiring",
          priority: "Medium",
          status: "Approved",
          action: "View",
        },
        {
          materialName: "Fuses & Relays",
          quantityRequested: 12,
          requestedTo: "Engineering",
          dateOfRequirement: "2025-03-13",
          materialPurpose: "Circuit protection",
          priority: "High",
          status: "Pending",
          action: "Approve",
        },
        {
          materialName: "Solar Panels",
          quantityRequested: 2,
          requestedTo: "Renewable Energy Dept",
          dateOfRequirement: "2025-03-15",
          materialPurpose: "Energy efficiency upgrade",
          priority: "Critical",
          status: "Pending",
          action: "Approve",
        },
      ],
    },
    {
      id: 2,
      sno: 2,
      reqId: "REQ-1002",
      materialsCount: 2,
      description: "Order for plumbing materials",
      dateOfReq: "2025-02-27",
      status: "Approved",
      nestedData: [
        {
          materialName: "PVC Pipes",
          quantityRequested: 30,
          requestedTo: "Plumbing Dept",
          dateOfRequirement: "2025-03-03",
          materialPurpose: "Pipeline extension",
          priority: "High",
          status: "Approved",
          action: "View",
        },
        {
          materialName: "Fittings & Valves",
          quantityRequested: 15,
          requestedTo: "Maintenance",
          dateOfRequirement: "2025-03-05",
          materialPurpose: "Water flow control",
          priority: "Medium",
          status: "Pending",
          action: "Approve",
        },
      ],
    },
    {
      id: 3,
      sno: 3,
      reqId: "REQ-1003",
      materialsCount: 1,
      description: "Request for construction tools",
      dateOfReq: "2025-02-25",
      status: "Rejected",
      nestedData: [
        {
          materialName: "Concrete Mixer",
          quantityRequested: 1,
          requestedTo: "Construction",
          dateOfRequirement: "2025-03-02",
          materialPurpose: "Foundation work",
          priority: "Critical",
          status: "Rejected",
          action: "Reapply",
        },
      ],
    },
  ];
  
  export default MaterialRequestMockData;
  
 